### ISSUE TITLE
Use of Main Tag 

### ISSUE THREAD

**Issue by JEFFKAY16** [sja-thedude/Project-Portfolio-setup-and-mobile-version-skeleton#6]
## Use of Main Tag 
Excellent work SJA, I like the fact that you've used semantic tags throughout your codebase. Keep it up!

In this peer-to-peer review, I noted:

- It would also be nice to have a `main` tag used at line 35 to replace the `section` tag. It being a home page, the `main` tag would be well suited for it. Otherwise, excellent work!

**Comment by sja-thedude** [comment]
Thanks for your feedback!
